# STIG Manager with CAC Authentication using HAProxy

version: '3.7'

services:
  haproxy:
    image: haproxy:2.8-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/combined.pem:/usr/local/etc/haproxy/certs/combined.pem:ro
      - ./certs/dod/DoD_Root_CAs.pem:/usr/local/etc/haproxy/certs/dod-certs.pem:ro
      - ./haproxy/index.html:/usr/local/etc/haproxy/index.html:ro
    ports:
      - "443:443"
    depends_on:
      - keycloak
      - stigman

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    # alternative image from Ironbank
    # image: registry1.dso.mil/ironbank/opensource/keycloak/keycloak:19.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://localhost/kc/
      - KC_HOSTNAME_ADMIN_URL=https://localhost/kc/
      - KC_SPI_X509CERT_LOOKUP_PROVIDER=apache
      - KC_SPI_X509CERT_LOOKUP_APACHE_SSL_CLIENT_CERT=ssl-client-cert
    command: start --import-realm
    volumes:
      - ./kc/stigman_realm.json:/opt/keycloak/data/import/stigman_realm.json
      - ./kc/create-x509-user.jar:/opt/keycloak/providers/create-x509-user.jar
      # uncomment below to persist Keycloak data
      # - ./kc/h2:/opt/keycloak/data/h2

  stigman:
    image: nuwcdivnpt/stig-manager:1.5.13
    # alternative image based on Ironbank Node.js
    # image: nuwcdivnpt/stig-manager:latest-ironbank
    environment:
      - STIGMAN_OIDC_PROVIDER=http://keycloak:8080/realms/stigman
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://localhost/kc/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=mysql
      - STIGMAN_DB_USER=stigman
      - STIGMAN_DB_PASSWORD=stigmanpw
    init: true

  mysql:
    image: mysql:8.0.38
    # alternative image from Ironbank
    # image: registry1.dso.mil/ironbank/opensource/mysql/mysql8:8.0.31
    command: --innodb-buffer-pool-size=512M --sort_buffer_size=64M
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_DATABASE=stigman
      - MYSQL_PASSWORD=stigmanpw
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
